# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseflow
spec:
  replicas: 2 # testing with two for now
  selector:
    matchLabels:
      app: courseflow
  template:
    metadata:
      labels:
        app: courseflow
    spec:
      containers:
      - name: courseflow
        image: averwhy/courseflow:loadtest-v1
        envFrom:
          - secretRef:
              name: courseflow-env
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"